### ISSUE TITLE
Implement new reserve site design + fetch data

### ISSUE THREAD

**Issue by cmcewen** [celo-org/reserve-site#10]
https://docs.google.com/document/d/1nxWZaW7Vh9XqURzh1-4sQK2sNGAqWhPeggEOBIar5uQ/edit

**Comment by aaronmgdr** [comment]
TODO: 
* fetch non celo addresses from airtable and use it look up the balances for those tokens 
* get frozen and unfrozen balances from contract kit 
* hide cEUR until its out
* make sure not to overwrite caches with null responses
* make sure in compliance with all third party apis
* setup figment as backup to forno? 
* ensure that we dont request the same data from our providers multiple times. (data loader?)
